# Generated by Django 3.0.6 on 2020-09-11 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_book', models.CharField(max_length=100, verbose_name='Название книги')),
                ('author_book', models.CharField(max_length=100, verbose_name='Автор книги')),
                ('date_book', models.IntegerField(blank=True, null=True, verbose_name='Год книги')),
                ('description_book', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание книги')),
                ('image_book', models.ImageField(blank=True, upload_to='image/', verbose_name='Изображение книги')),
                ('pdf_book', models.FileField(blank=True, upload_to='pdf/', verbose_name='Ссылка pdf')),
                ('date_publication', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('like_publication', models.BigIntegerField(default=0, verbose_name='Себе')),
                ('like_author', models.BooleanField(default=False)),
                ('author_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200, verbose_name='текст комментария')),
                ('comment_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='время комментария')),
                ('comment_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='комментатор')),
                ('comment_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSocialNetwork.Book', verbose_name='публикация')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
