# Generated by Django 3.0.7 on 2020-08-29 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appSocialNetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
