# Generated by Django 3.0.6 on 2020-09-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSocialNetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(verbose_name='текст комментария'),
        ),
    ]
