# Generated by Django 3.0.6 on 2022-06-05 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appSocialNetwork', '0004_auto_20210620_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='like_author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='like_publication',
        ),
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
